# Generate a Go overlay without modifying the module cache or vendored sources.
# Also usable with cmake -DGO_WIREGUARD_DIR=... -DGO_OVERLAY_DIR=... -P ...
if(NOT EXISTS "${GO_WIREGUARD_DIR}/conn/bind_windows.go")
    message(FATAL_ERROR "WireGuard Windows bind source not found: ${GO_WIREGUARD_DIR}")
endif()
file(MAKE_DIRECTORY "${GO_OVERLAY_DIR}")
file(READ "${GO_WIREGUARD_DIR}/conn/bind_windows.go" _bind_source)
set(_old "return NewWinRingBind(externalControl)")
set(_new "return newIPv4FallbackBind(externalControl)")
string(FIND "${_bind_source}" "${_old}" _bind_pos)
if(_bind_pos EQUAL -1)
    message(FATAL_ERROR "WireGuard bind changed; review the IPv4 fallback overlay")
endif()
string(REPLACE "${_old}" "${_new}" _bind_source "${_bind_source}")
file(WRITE "${GO_OVERLAY_DIR}/bind_windows.go" "${_bind_source}")
file(READ "${GO_WIREGUARD_DIR}/conn/bind_std.go" _std_source)
set(_old "v6conn, port, err = listenNet(s.externalControl, \"udp6\", port)")
set(_new "ipv4Port := port\n\tv6conn, port, err = listenNet(s.externalControl, \"udp6\", port)\n\tif v6conn == nil && errors.Is(err, syscall.EAFNOSUPPORT) {\n\t\tport = ipv4Port\n\t}")
string(FIND "${_std_source}" "${_old}" _bind_pos)
if(_bind_pos EQUAL -1)
    message(FATAL_ERROR "WireGuard standard bind changed; review port preservation")
endif()
string(REPLACE "${_old}" "${_new}" _std_source "${_std_source}")
file(WRITE "${GO_OVERLAY_DIR}/bind_std.go" "${_std_source}")
file(TO_CMAKE_PATH "${GO_WIREGUARD_DIR}" _module)
file(TO_CMAKE_PATH "${GO_OVERLAY_DIR}" _output)
file(TO_CMAKE_PATH "${CMAKE_CURRENT_LIST_DIR}" _patch)
set(_replace "\"${_module}/conn/bind_windows.go\": \"${_output}/bind_windows.go\",\n\"${_module}/conn/bind_std.go\": \"${_output}/bind_std.go\",\n\"${_module}/conn/nekobox_ipv4_fallback_windows.go\": \"${_patch}/ipv4_fallback_windows.go\"")
if(GO_OVERLAY_TESTS)
    string(APPEND _replace ",\n\"${_module}/conn/nekobox_ipv4_fallback_windows_test.go\": \"${_patch}/ipv4_fallback_windows_test.go\"")
endif()
file(WRITE "${GO_OVERLAY_DIR}/overlay.json" "{\"Replace\": {${_replace}}}\n")
